theme: minimal-mistakes-jekyll
title: '{{ blog_name_here }}'
author: Kevin W Matthews
author_url: https://www.kevinwmatthews.com
description:
  Exploring software development and design. Actual code included.
include:
  - _pages
exclude:
  - .bundle
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
search: true
search_full_content: true
