theme: minimal-mistakes-jekyll
title: '{{ blog_name_here }}'
author: Kevin W Matthews
author_url: https://www.kevinwmatthews.com
description:
  Exploring software development and design. Actual code included.
include:
  - _pages
exclude:
  - .bundle
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
