theme: minimal-mistakes-jekyll

# Site settings
title: '{{ blog_name_here }}'
name: &name Kevin W Matthews
description: &description Exploring software development and design. Actual code included.

# Site author
author:
  name: *name   # Point to &anchor above

# Files to serve
include:
  - _pages
exclude:
  - .bundle
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Default settings
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single

# Post archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Site search
search: true
search_full_content: true
