theme: minima
title: '{{ blog_name_here }}'
author: Kevin W Matthews
description:
    In search of well-crafted code.
header_pages:
    - about-me.md
    - about-this-blog.md
permalink: /:title
collections:
    posts:
        permalink: /post/:title
